framework:
    workflows:
        conge_status:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'statut'
            supports:
                - App\Entity\Conge
            places:
                - en_attente
                - approuvé
                - refusé
                - annulé
            transitions:
                approve:
                    from: en_attente
                    to: approuvé
                refuse:
                    from: en_attente
                    to: refusé
                cancel:
                    from: [approuvé, refusé]
                    to: annulé